# General Jekyll Config
highlighter: rouge
url: https://Chun-Ge.github.io
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]

title: Chun-Ge's Github Page
description: > # this means to ignore newlines until next config entry
  Organization Blog of Chun-Ge, for SYSU-SSAD Course Project

encoding: utf-8

permalink: ':title/'
